# Dependencies, themes, etc.
import = [
	"~/.config/alacritty/themes/tokyo-storm.toml"
]

[font]
size = 20

[font.normal]
family = "Fantasque Sans Mono"

[window]
# decorations = "none"

[window.padding]
x = 8
y = 0
