# Dependencies, themes, etc.
import = [
	"~/.config/alacritty/themes/tokyo-storm.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[window]
opacity = 0.8
blur = true
option_as_alt = "Both"
padding = {x = 12, y = 12}
