#!/bin/bash

### Aliases

# Human readable, indicators and no group names for `ls`
alias ls='ls -GFh'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

### PATH variable

# Setting PATH for Python 3.6 - The original version is saved in .bash_profile.pysave
export PATH="$HOME/.bin:/usr/local/bin/git:/usr/local/bin:/usr/bin\
:/Applications/Visual Studio Code.app/Contents/Resources/app/bin\
:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin\
:$HOME/.npm/bin:$HOME/.config/npm/global/node_modules/.bin\
:$PATH
"

### Init pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# This is slow-running, but uncomment if you want
# eval "$(pyenv init -)"

source ~/.nvm/nvm.sh

# Source profile
. ~/.bash_profile
. "$HOME/.cargo/env"
